<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DELL" name="Test3" tests="1" failures="1" timestamp="12 Oct 2020 08:38:19 GMT" time="162.156" errors="0">
  <testcase name="instaFailTest" time="0.005" classname="Instagram.E2EIns.InstaTest3">
    <failure type="java.lang.AssertionError" message="Test Failed">
      <![CDATA[java.lang.AssertionError: Test Failed
	at Instagram.E2EIns.InstaTest3.instaFailTest(InstaTest3.java:42)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- instaFailTest -->
</testsuite> <!-- Test3 -->
